include .env
export

.PHONY: ssh terraform-init terraform-plan terraform-apply deploy-certs

SSH := C:\WINDOWS\Sysnative\OpenSSH\ssh.exe
SCP := C:\WINDOWS\Sysnative\OpenSSH\scp.exe

ssh:
	$(SSH) -i $(DEPLOY_SSH_KEY) $(DEPLOY_USER)@$(DEPLOY_HOST)

# ─── Terraform ────────────────────────────────────────────────────────────────

TF_DIR := terraform
TF := cd $(TF_DIR) && terraform

terraform-init:
	$(TF) init

terraform-plan:
	$(TF) plan

terraform-apply:
	$(TF) apply

# Upload TLS certificates generated by Terraform to the server.
# Run after `make terraform-apply`.
deploy-certs:
	$(SCP) -i $(DEPLOY_SSH_KEY) terraform/.certs/laravel.carocholab.com.pem $(DEPLOY_USER)@$(DEPLOY_HOST):/etc/nginx/ssl/
	$(SCP) -i $(DEPLOY_SSH_KEY) terraform/.certs/laravel.carocholab.com.key $(DEPLOY_USER)@$(DEPLOY_HOST):/etc/nginx/ssl/
	$(SCP) -i $(DEPLOY_SSH_KEY) terraform/.certs/laravel-dev.carocholab.com.pem $(DEPLOY_USER)@$(DEPLOY_HOST):/etc/nginx/ssl/
	$(SCP) -i $(DEPLOY_SSH_KEY) terraform/.certs/laravel-dev.carocholab.com.key $(DEPLOY_USER)@$(DEPLOY_HOST):/etc/nginx/ssl/
	$(SSH) -i $(DEPLOY_SSH_KEY) $(DEPLOY_USER)@$(DEPLOY_HOST) "nginx -t && systemctl reload nginx"
